server:
  port: 8081

spring:
  application:
    name: mall

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 032581
  data:
    redis:
          host: localhost
          port: 6379
          database: 0
          timeout: 3000ms
  rabbitmq:
    host: localhost
    port: 15673
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
        concurrency: 2
        max-concurrency: 4
        default-requeue-rejected: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mall:
  name: mall
  version: 0.4
  order:
    max-quantity: 100
  jwt:
    secret: "MallX-Development-Secret-Key-Change-Me-2026-At-Least-32-Bytes"
    expiration: 7200000
  seckill:
    rate-limit:
      enabled: true

      user:
        capacity: 5
        refill-rate: 2

      ip:
        capacity: 30
        refill-rate: 10

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: Mall
    version: 0.29
    description: Happy New Year