---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lyp.
--- DateTime: 2026/9/4 18:01
---

-- 已经处理过
if redis.call('EXISTS',KEYS[2]) == 1 then
    return 0
end

-- 增加成交量
redis.call(
        'ZINCRBY',
        KEYS[1],
        ARGV[2],
        ARGV[1]
)

-- 记录 eventId, 避免 MQ 重复消费重复增加
redis.call(
        'SET',
        KEYS[2],
        '1',
        'EX',
        ARGV[3]
)

return 1