---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lyp.
--- DateTime: 2026/8/30 23:50
---

local purchased = redis.call('SISMEMBER',KEYS[2],ARGV[1])

if purchased == 1 then
    redis.call('INCR',KEYS[1])
    redis.call('SREM',KEYS[2],ARGV[1])

    return 1
end

return 0