---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lyp.
--- DateTime: 2026/8/30 23:41
---

local redisTime = redis.call('Time')

local now = tonumber(redisTime[1])

local startTime = tonumber(ARGV[2])

local endTime = tonumber(ARGV[3])

if now < startTime then
    return 4
end

if now >= endTime then
    return 5
end

local stock = redis.call('GET',KEYS[1])

if not stock then
    return 3
end

if tonumber(stock) <= 0 then
    return 1
end

local purchased = redis.call('SISMEMBER',KEYS[2],ARGV[1])

if purchased == 1 then
    return 2
end

redis.call('DECR',KEYS[1])

redis.call('SADD',KEYS[2],ARGV[1])

local exprieAt = tonumber(ARGV[4])

if exprieAt > 0 then
    redis.call('EXPIREAT',KEYS[1],exprieAt)
    redis.call('EXPIREAT',KEYS[2],exprieAt)
end

return 0
